baseURL = ""
languageCode = "en"
DefaultContentLanguage = "en"

title = "Amy Janis"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

weight = 1
LanguageName = "EN"
contentDir = "content"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
